name: Deploy to Production

on:
  push:
    branches:
      - main 
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    if: contains(github.event.head_commit.message, 'prod-build')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Run Build for Production
        run: npm run build:prod

      - name: Deploy to Vercel Production
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_PRODUCTION }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}

      - name: Notify on Telegram - Success
        if: success()
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="✅ Build Succeeded for repository: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nCommit: ${{ github.sha }}\nCommit message: ${{ github.event.head_commit.message }}"


      - name: Notify on Telegram - Failure
        if: failure()
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="❌ Build Failed for repository: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nCommit: ${{ github.sha }}\nCommit message: ${{ github.event.head_commit.message }}\nError: ${{ job.status }}"
          
