name: Deploy to Production

on:
  push:
    branches:
      - main 
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    if: contains(github.event.head_commit.message, 'prod-build')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Run Build for Production
        run: npm run build:prod

      - name: Deploy to Vercel Production
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_PRODUCTION }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}
          
      - name: build notifier
        run : | 
        echo "building project"
      
      - name: Notify on telegram
        if: success()
        run : |
           curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
        -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
        -d text="✅ Build Succeeded for techunter prod"

      - name : Notify Failure On telegram
        if : failure()
        run : |
           curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
        -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
        -d text="❌ Build Failed for techunter prod"

