name: Deploy to Staging

on:
  push:
    branches:
      - main 
    paths-ignore:
      - 'docs/**' 
  workflow_dispatch:

jobs:
  build:
    if: contains(github.event.head_commit.message, 'stage-build') 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Run Build for Staging
        run: npm run build:stage 

      - name: Deploy to Vercel Staging
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --scope techinters-projects --env NODE_ENV=staging
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_STAGING }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          DOMAIN: ${{ secrets.STAGING_DOMAIN }}
